### ISSUE TITLE
Add :broadcast to Ionian::Socket.new keyword args

### ISSUE THREAD

**Issue by jemc** [amclain/ionian#1]
Add `:broadcast` to Ionian::Socket.new keyword args.

Maybe broadcast should be set automatically if the host address given is a broadcast address?

Note that you get `Errno::EACCES` if `@socket.connect` is called with a broadcast address before the broadcast socket option is set, so if the keyword arg is there, the socket option should be set before connect.

**Comment by amclain** [comment]
Closed in 87832bf
